/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import mode.bean.Clientes;
import model.dao.ClientesDAO;

/**
 *
 * @author serpa
 */
public class ClienteView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClienteView
     */
    public ClienteView() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        DefaultTableModel modelo = (DefaultTableModel) jTClientes.getModel();
        jTClientes.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTClientes.getModel();
        modelo.setNumRows(0);
        ClientesDAO cdao = new ClientesDAO();
        
        for (Clientes c: cdao.read()){
            
            modelo.addRow(new Object[]{
                c.getCodigo(),
                c.getRazaoSocial(),
                c.getNomeFantasia(),
                c.getPessoa(),
                c.getCPF(),
                c.getCNPJ(),
                c.getInscricaoMunicipal(),
                c.getReferencia(),
                c.getTelefone(),
                c.getEmail(),
                c.getEndereco(),
                c.getCidade(),
                c.getBairro(),
                c.getOrgaoPublico(),
                c.getMicroempresa(),
                c.getInscricaoEstadual()
            });
        }
    }
    
    public void readJTableForName(String name){
        DefaultTableModel modelo = (DefaultTableModel) jTClientes.getModel();
        modelo.setNumRows(0);
        ClientesDAO cdao = new ClientesDAO();
        
        for (Clientes c: cdao.readForName(name)){
            
            modelo.addRow(new Object[]{
                c.getCodigo(),
                c.getRazaoSocial(),
                c.getNomeFantasia(),
                c.getPessoa(),
                c.getCPF(),
                c.getCNPJ(),
                c.getInscricaoMunicipal(),
                c.getReferencia(),
                c.getTelefone(),
                c.getEmail(),
                c.getEndereco(),
                c.getCidade(),
                c.getBairro(),
                c.getOrgaoPublico(),
                c.getMicroempresa(),
                c.getInscricaoEstadual()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        txtReferencia = new javax.swing.JTextField();
        txtNomeFantasia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbOrgaoPublico = new javax.swing.JComboBox();
        cbPessoa = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbMicroempresa = new javax.swing.JComboBox();
        txtCNPJ = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtInscEstadual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInscMunicipal = new javax.swing.JTextField();
        txtRazaoSocial = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Razão Social", "Nome Fantasia", "Pessoa", "CPF", "CNPJ", "Inscrição Municipal", "Referência", "Telefone", "Email", "Endereço", "Cidade", "Bairro", "Orgão Público", "Microempresa", "Inscrição Estadual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTClientes);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Referência");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 149, -1, -1));

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 295, -1));
        jPanel3.add(txtReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 169, 295, 66));
        jPanel3.add(txtNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 31, 295, -1));

        jLabel15.setText("Orgão Publico");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 164, -1, -1));

        jLabel4.setText("Pessoa");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 164, -1, -1));

        cbOrgaoPublico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Sim", "Não" }));
        jPanel3.add(cbOrgaoPublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 184, -1, -1));

        cbPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Física", "Jurídica" }));
        jPanel3.add(cbPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 184, -1, -1));

        jLabel16.setText("Microempresa");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 164, -1, -1));

        jLabel5.setText("CNPJ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 57, -1, -1));

        cbMicroempresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Sim", "Não" }));
        jPanel3.add(cbMicroempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 184, -1, -1));

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 77, 295, -1));

        jLabel6.setText("Inscrição Estadual/RG");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, -1, -1));

        jLabel1.setText("Razão Social");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));
        jPanel3.add(txtInscEstadual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 295, -1));

        jLabel2.setText("CPF");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, -1, -1));

        jLabel7.setText("Inscrição Municipal");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 103, -1, -1));

        jLabel3.setText("Nome Fantasia");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 11, -1, -1));
        jPanel3.add(txtInscMunicipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 123, 295, -1));
        jPanel3.add(txtRazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 295, -1));
        jPanel3.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 261, 295, -1));
        jPanel3.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 307, 295, -1));

        jLabel12.setText("Endereço");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 287, -1, -1));

        jLabel11.setText("E-mail");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 241, -1, -1));
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 261, 295, -1));

        jLabel14.setText("Bairro");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 337, -1, -1));
        jPanel3.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 362, 295, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 307, 295, -1));

        jLabel10.setText("Telefone");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 287, -1, -1));

        jLabel13.setText("Cidade");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 241, -1, -1));

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 393, -1, -1));
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 394, 285, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        Clientes c = new Clientes();
        ClientesDAO dao = new ClientesDAO();
        c.setRazaoSocial(txtRazaoSocial.getText());
        c.setNomeFantasia(txtNomeFantasia.getText());
        c.setPessoa(cbPessoa.getSelectedItem().toString());
        c.setCPF(txtCPF.getText());
        c.setCNPJ(txtCNPJ.getText());
        c.setInscricaoMunicipal(txtInscMunicipal.getText());
        c.setReferencia(txtReferencia.getText());
        c.setTelefone(txtTelefone.getText());
        c.setEmail(txtEmail.getText());
        c.setEndereco(txtEndereco.getText());
        c.setCidade(txtCidade.getText());
        c.setBairro(txtBairro.getText());
        c.setOrgaoPublico(cbOrgaoPublico.getSelectedItem().toString());
        c.setMicroempresa(cbMicroempresa.getSelectedItem().toString());
        c.setInscricaoEstadual(txtInscEstadual.getText());
        dao.create(c);
        
        txtRazaoSocial.setText("");
        txtNomeFantasia.setText("");
        cbPessoa.setSelectedIndex(0);
        txtCPF.setText("");
        txtCNPJ.setText("");
        txtInscMunicipal.setText("");
        txtReferencia.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtReferencia.setText("");
        txtCidade.setText("");
        txtBairro.setText("");
        txtEmail.setText("");
        cbOrgaoPublico.setSelectedIndex(0);
        cbMicroempresa.setSelectedIndex(0);
        txtInscEstadual.setText("");
        
        readJTable();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jTClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseClicked
        
         if(jTClientes.getSelectedRow() != -1){
        txtRazaoSocial.setText("");
        txtNomeFantasia.setText("");
        cbPessoa.setSelectedIndex(0);
        txtCPF.setText("");
        txtCNPJ.setText("");
        txtInscMunicipal.setText("");
        txtReferencia.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtReferencia.setText("");
        txtCidade.setText("");
        txtBairro.setText("");
        cbOrgaoPublico.setSelectedIndex(0);
        cbMicroempresa.setSelectedIndex(0);
        txtInscEstadual.setText("");
            txtRazaoSocial.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 1).toString());
            txtNomeFantasia.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 2).toString());
            cbPessoa.setSelectedItem(jTClientes.getValueAt(jTClientes.getSelectedRow(), 3).toString());
            txtCPF.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 4).toString());
            txtCNPJ.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 5).toString());
            txtInscMunicipal.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 6).toString());
            txtReferencia.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 7).toString());
            txtTelefone.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 8).toString());
            txtEmail.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 9).toString());
            txtEndereco.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 10).toString());
            txtCidade.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 11).toString());
            txtBairro.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 12).toString());
            cbOrgaoPublico.setSelectedItem(jTClientes.getValueAt(jTClientes.getSelectedRow(), 13).toString());
            cbMicroempresa.setSelectedItem(jTClientes.getValueAt(jTClientes.getSelectedRow(), 14).toString());
            txtInscEstadual.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 15).toString());
        }
    }//GEN-LAST:event_jTClientesMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(jTClientes.getSelectedRow() != -1){
            
        Clientes c = new Clientes();
        ClientesDAO dao = new ClientesDAO();
        c.setRazaoSocial(txtRazaoSocial.getText());
        c.setNomeFantasia(txtNomeFantasia.getText());
        c.setPessoa(cbPessoa.getSelectedItem().toString());
        c.setCPF(txtCPF.getText());
        c.setCNPJ(txtCNPJ.getText());
        c.setInscricaoMunicipal(txtInscMunicipal.getText());
        c.setReferencia(txtReferencia.getText());
        c.setTelefone(txtTelefone.getText());
        c.setEmail(txtEmail.getText());
        c.setEndereco(txtEndereco.getText());
        c.setCidade(txtCidade.getText());
        c.setBairro(txtBairro.getText());
        c.setOrgaoPublico(cbOrgaoPublico.getSelectedItem().toString());
        c.setMicroempresa(cbMicroempresa.getSelectedItem().toString());
        c.setInscricaoEstadual(txtInscEstadual.getText());
        c.setCodigo((int) jTClientes.getValueAt(jTClientes.getSelectedRow(), 0));
        dao.update(c);
        
        txtRazaoSocial.setText("");
        txtNomeFantasia.setText("");
        cbPessoa.setSelectedIndex(0);
        txtCPF.setText("");
        txtCNPJ.setText("");
        txtInscMunicipal.setText("");
        txtReferencia.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtReferencia.setText("");
        txtCidade.setText("");
        txtBairro.setText("");
        txtEmail.setText("");
        cbOrgaoPublico.setSelectedIndex(0);
        cbMicroempresa.setSelectedIndex(0);
        txtInscEstadual.setText("");
        
        
        
        readJTable();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        if(jTClientes.getSelectedRow() != -1){
         Clientes c = new Clientes();
        ClientesDAO dao = new ClientesDAO();
        c.setCodigo((int) jTClientes.getValueAt(jTClientes.getSelectedRow(), 0));
        dao.delete(c);
        
        txtRazaoSocial.setText("");
        txtNomeFantasia.setText("");
        cbPessoa.setSelectedIndex(0);
        txtCPF.setText("");
        txtCNPJ.setText("");
        txtInscMunicipal.setText("");
        txtReferencia.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtReferencia.setText("");
        txtCidade.setText("");
        txtBairro.setText("");
        txtEmail.setText("");
        cbOrgaoPublico.setSelectedIndex(0);
        cbMicroempresa.setSelectedIndex(0);
        txtInscEstadual.setText("");
        
        
        
        readJTable();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
//        
//        txtRazaoSocial.setText("");
//        txtNomeFantasia.setText("");
//        cbPessoa.setSelectedIndex(0);
//        txtCPF.setText("");
//        txtCNPJ.setText("");
//        txtInscMunicipal.setText("");
//        txtReferencia.setText("");
//        txtTelefone.setText("");
//        txtEndereco.setText("");
//        txtReferencia.setText("");
//        txtCidade.setText("");
//        txtBairro.setText("");
//        txtEmail.setText("");
//        cbOrgaoPublico.setSelectedIndex(0);
//        cbMicroempresa.setSelectedIndex(0);
//        txtInscEstadual.setText("");
    }//GEN-LAST:event_jPanel3MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        txtRazaoSocial.setText("");
        txtNomeFantasia.setText("");
        cbPessoa.setSelectedIndex(0);
        txtCPF.setText("");
        txtCNPJ.setText("");
        txtInscMunicipal.setText("");
        txtReferencia.setText("");
        txtTelefone.setText("");
        txtEndereco.setText("");
        txtReferencia.setText("");
        txtCidade.setText("");
        txtBairro.setText("");
        txtEmail.setText("");
        cbOrgaoPublico.setSelectedIndex(0);
        cbMicroempresa.setSelectedIndex(0);
        txtInscEstadual.setText("");
    }//GEN-LAST:event_formMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        readJTableForName(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox cbMicroempresa;
    private javax.swing.JComboBox cbOrgaoPublico;
    private javax.swing.JComboBox cbPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTClientes;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtInscEstadual;
    private javax.swing.JTextField txtInscMunicipal;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
